### ISSUE TITLE
Support for databases in Feather v2 format?

### ISSUE THREAD

**Issue by SL1993** [aertslab/RcisTarget#28]
Hi,
noticed that feather databases have been updated to V2 recently. Will Rcistarget support this new version of database in the future?
Many thanks!

**Comment by s-aibar** [comment]
Dear @SL1993 , 

RcisTarget has supported feather v2 format for a few releases. If you are getting an error when using the new version of the databases, it is probably because of the different column names. That error will be solved with the next Bioconductor release (on Nov. 2), but meanwhile you can use the argument `indexCol='motif'` from `importRankings()`.

Sorry for the inconvenience,
Sara
