### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by eblchen** [aertslab/RcisTarget#39]
I'm having issues install RcisTarget using:
```
BiocManager::install("RcisTarget")
```
The warning message is as follows:
```
Warning message:
package ‘RcisTarget’ is not available for Bioconductor version '3.18'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

**Comment by lodimk2** [comment]
I have the same issue..

**Comment by NPotvin** [comment]
Hello,
it seems the tar.gz is missing from the Bioconductor repository (here https://bioconductor.org/packages/release/bioc/html/RcisTarget.html)

**Comment by boegel** [comment]
This issue shouldn't be closed, because the actual problem is not resolved at all...

The source tarball for `RcisTarget` 1.22.0 are not available via Bioconductor the way it should be, that should be fixed.

Although downloading via https://code.bioconductor.org/browse/RcisTarget/tarball/RELEASE_3_18 works, the file obtained that way is not exactly the same every time, so there's no way to check whether the download was correct or not (can't rely on a checksum).

@aertslab @s-aibar please fix this?

**Comment by sassy-crick** [comment]
To add what @boegel wrote: I got the same issue with the installation and the suggested 'solution' is not a good one. Science lives from reproducibility and if we cannot reproduce our installations, can how can we trust our results obtained with the software? The answer is we can not. Why was that tarball removed in the first place?

@aertslab @s-aibar @nturaga  could you please re-open that issue and fix it properly? Thanks!
