### ISSUE TITLE
Motif coordinates?

### ISSUE THREAD

**Issue by jfreimer** [aertslab/RcisTarget#7]
I am using RcisTarget to infer transcription factors that regulate a list of genes. I have a few candidate transcription factors from RcisTarget and their target genes. I'd like to get the mouse genomic coordinates for the predicted location of a motif upstream of it's target genes so that I can overlap it with some ATAC-seq data that we have. I didn't see anywhere that listed genomic coordinates for each motif and was wondering if this file exists?

**Comment by s-aibar** [comment]
There isn't a database with the genomic coordinates of each motif in each gene/target. The rankings are built based on the the enrichment of the motif (mostly the score of CRMs). Since the CRMs include multiple instances of the motif, and we do not use a threshold for the score (e.g. the ranking goes from best to worst score), the results from this analysis are huge (not feasible to distribute to end users) and it is not straight forward to provide a list of instances of motif per gene (e.g. to create a database).

If you are really interested in finding instances of a motif for a specific gene, then you can score the motif yourself with tools such as Homer or RSat (or in R...). If you have a set of genes (e.g. a regulon) you can try analysing it with [i-cisTarget](https://gbiomed.kuleuven.be/apps/lcb/i-cisTarget/): once you get the results of the analysis, you can select a specific motif and click "Scan candidate target regions of selected features for homotypic CRMs" (it is not exactly what you are looking for, but it might be close enough...).
